FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_producer/ ./kafka_producer
COPY data/simulated_tweets_with_geo.json /data/simulated_tweets_with_geo.json

CMD ["python", "kafka_producer/producer.py"]
