resources:
  - type: "ambulance"
    max_capacity: 5
  - type: "medical_team"
    max_capacity: 10
  - type: "shelter"
    max_capacity: 100

models:
  allocation_model: "path/to/ibm_granite_model"
  social_media_data_source: "twitter"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
