resources:
  - type: "ambulance"
    max_capacity: 5
  - type: "medical_team"
    max_capacity: 10
  - type: "shelter"
    max_capacity: 100

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

model:
  name: ibm-granite/granite-3.3-2b-base
  token_env_var: HF_TOKEN
thresholds:
  sentiment: 0.5
  crisis_ratio: 0.1
